version: "3.8"

services:
  medusaapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: medusa-backend
    environment:
      - DB_HOST=${POSTGRES_DB_HOST}
      - DB_PORT=${POSTGRES_DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${POSTGRES_DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_URL=redis://${REDIS_SERVICE_NAME}:${REDIS_SERVICE_PORT}/5
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - PORT=9000
    networks:
      - postgres-shared-network
      - frappe-shared-network
      - traefik-public
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.medusa-backend.rule=Host(`shop-api.${DOMAIN_NAME}`)"
      - "traefik.http.routers.medusa-backend.entrypoints=websecure"
      - "traefik.http.routers.medusa-backend.tls.certresolver=myresolver"
      - "traefik.http.services.medusa-backend.loadbalancer.server.port=9000"

networks:
  postgres-shared-network:
    external: true
  frappe-shared-network:
    external: true
  traefik-public:
    external: true
