version: "3.8"

services:
  storefront:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs-storefront-prod
    environment:
      - NEXT_PUBLIC_MEDUSA_BACKEND_URL=https://shop-api.${DOMAIN_NAME}
    networks:
      - traefik-public
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.storefront.rule=Host(`shop.${DOMAIN_NAME}`)"
      - "traefik.http.routers.storefront.entrypoints=websecure"
      - "traefik.http.routers.storefront.tls.certresolver=myresolver"
      - "traefik.http.services.storefront.loadbalancer.server.port=3000"

networks:
  traefik-public:
    external: true
